FROM golang:latest AS builder
WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build --ldflags="-w -s" -o zip cmd/service-a/main.go

FROM alpine:latest
COPY --from=builder /app/zip /app/zip
CMD ["/app/zip"]