services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    networks:
      - otel

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    restart: always
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    networks:
      - otel

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - /Users/aricamargo/repos/fullcycle/fullcycle-otel/.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - otel

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - /Users/aricamargo/repos/fullcycle/fullcycle-otel/.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OTLP gRPC receiver
    networks:
      - otel

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - otel

  service-a:
    container_name: service-a
    restart: unless-stopped
    # command: tail -f /dev/null
    build:
      context: .
      dockerfile: Dockerfile.service-a
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8080
    ports:
      - "8080:8080"
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - otel-collector
    networks:
      - otel

  service-b:
    container_name: service-b
    restart: unless-stopped
    # command: tail -f /dev/null
    build:
      context: .
      dockerfile: Dockerfile.service-b
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8081
    ports:
      - "8081:8081"
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - otel-collector
    networks:
      - otel

networks:
  otel:
    driver: bridge
